[project]
name = "zizmor-pre-commit"
version = "0.0.0"
requires-python = ">=3.10"
dependencies = [
    "zizmor==1.22.0",
]

[project.optional-dependencies]
dev = [
    "packaging~=23.1",
    "urllib3>=2.0.5,<3.0.0",
]
